# Generated by Django 3.0.2 on 2020-04-18 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.DateField(auto_now_add=True)),
                ('district', models.CharField(max_length=10)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('measure', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.city')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.items')),
            ],
        ),
    ]
