# Generated by Django 3.0.2 on 2020-04-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200419_0104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='item_name',
            new_name='description',
        ),
        migrations.AddField(
            model_name='items',
            name='element_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='items',
            unique_together={('element_name',)},
        ),
    ]
