# Generated by Django 3.0.2 on 2020-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_auto_20200419_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='time_unit',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
