# Generated by Django 3.0.2 on 2020-04-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_series_time_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('city', 'items', 'measure', 'start_time')},
        ),
    ]
