# Generated by Django 3.0.5 on 2020-04-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20200423_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='sights',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('elong', models.FloatField()),
                ('nlat', models.FloatField()),
                ('introduction', models.TextField()),
                ('target', models.CharField(max_length=30)),
                ('images', models.TextField()),
                ('url', models.TextField()),
                ('sourceType', models.IntegerField()),
            ],
            options={
                'unique_together': {('name', 'address')},
            },
        ),
    ]
