# Generated by Django 3.0.5 on 2020-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_sights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sights',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
