# Generated by Django 3.0.5 on 2020-04-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_auto_20200424_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sights',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
